# Generated by Django 5.2.17 on 2026-09-13 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('station', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('train_type', models.CharField(choices=[('SUPERFAST', 'SUPERFAST'), ('PASSENGER', 'PASSENGER'), ('MEMU', 'MEMU'), ('EXPRESS', 'EXPRESS')], max_length=15)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('ending_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trains_ending', to='station.station')),
                ('starting_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trains_starting', to='station.station')),
            ],
        ),
        migrations.CreateModel(
            name='TrainStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField()),
                ('arrival_time', models.TimeField()),
                ('departure_time', models.TimeField()),
                ('distance_from_origin', models.PositiveIntegerField(default=0)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='train_stations', to='station.station')),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stations', to='trains.train')),
            ],
        ),
    ]
