# Generated by Django 5.2.17 on 2026-09-13 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('station', '0002_alter_station_name'),
        ('trains', '0002_alter_train_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_from_nearest_station', models.IntegerField(default=0)),
                ('has_started', models.BooleanField(default=False)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('nearest_station', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='train_at_nearest_station', to='station.station')),
                ('previous_station', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='previous_station_trains', to='station.station')),
                ('train', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='trains.train')),
                ('upcoming_station', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next_station_trains', to='station.station')),
            ],
        ),
    ]
